---
name: Build with ncc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm and package
        run: |
          # Get github branch without refs
          GITHUB_BRANCH=$( echo "${{ github.ref }}" | sed 's/refs\/heads\///g' )
          echo "GITHUB_BRANCH=$GITHUB_BRANCH" >> "$GITHUB_ENV"
        
          # Install npm, ncc and build
          npm install
          npm i -g @vercel/ncc
          npm run package
      - name: commit and push
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"
          if [[ $(git diff | wc -c) -eq 0 ]]; then
            git add -A
            git commit -m "Update ncc build to latest version"
            git push origin HEAD
          else
            echo no changes
          fi
          